language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - 14
  - 12
  - 10
cache:
  directories:
    - node_modules
    - frontend/node_modules
    - server/node_modules
stages:
  - Server Test Lint
  - Frontend Test Lint
  - test
  - integration

jobs:
  include:
    - stage: 'Server Test Lint'
      before_install: cd server
      script: npm run lint

    - stage: 'Frontend Test Lint'
      before_install: cd frontend
      script: npm run lint