language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
    - frontend/node_modules
    - server/node_modules
stages:
  - Frontend Test
  - Server Test

jobs:
  include:
    - stage: 'Frontend Test'
      before_install: cd frontend
      script: npm run lint && npm run test
    
    - stage: 'Server Test'
      before_install: cd server
      script: npm run lint && npm run test
